### PR TITLE
Rebase Thomas Daede's m68k patches on top of fixed CI

### PR DESCRIPTION
**Pull request by keith-packard**

### CODE REVIEW

**Comment by tdaede** [comment]
Looks good. (how did you find the eiisinf thing? did a test fail?)

**Comment by keith-packard** [comment]
> Looks good. (how did you find the eiisinf thing? did a test fail?)

one of the build tests failed -- this is in the legacy stdio code when you enable long double output. Not a big deal, but nice to have it at least not failing.

**Comment by keith-packard** [comment]
So, there are still a few things that could be done to improve this port:

 * Add floating point exception support
 * Add custom math routines that use the 68881 for all of the supported operations

Obviously not critical, especially if you're not using floating point :-)

**Comment by keith-packard** [comment]
oh, and if you get really excited, figuring out a way to run tests under qemu would be super cool.

**Pull request merged**
