### PR TITLE
CI: use ccache on macOS

### PR DESCRIPTION
**Pull request by pjonsson**
Add a dependabot configuration that automatically makes pull requests when Github actions have new versions available.

Add ccache support to CMakeLists.txt and the CI for macOS.

### CODE REVIEW

**Comment by pjonsson** [comment]
This needs one more revision, will do that later tonight.

**Comment by keith-packard** [comment]
Do we need to avoid having parallel runs step on each others cache? Or is there some way to share cache results across them? I launched a rebuild of one run to see how effective the cache was in reducing overall time; when the cache is empty, it's a pretty big performance hit.

**Comment by pjonsson** [comment]
You're right, the jobs are stepping on each other's caches right now. The empty cache is slow as you say, but my experience is that even changing "core" include files in a repository still gives reasonable hit rates for the cache, so ccache is almost always a win after the cache is populated.

I haven't analyzed the sizes in the cache, but it might be possible to give each job their own cache. You mentioned the alternative of slicing the jobs in the other direction [here](https://github.com/picolibc/picolibc/pull/548#issuecomment-1690639702). It doesn't have to be a single job per architecture though, it could be a few jobs per architecture.

**Comment by keith-packard** [comment]
Do you want to split out the docker compression patch into a separate PR? We can use that right away.

**Comment by pjonsson** [comment]
This is the parts of the initial PR that are a strict improvement over what is currently in main.

The "MacOS" test job takes 1m 17s with a warm cache for this PR, compared to 2m 30s for the latest macOS CI job that ran on main. The additional time in the steps by the ccache action is 17s, where 16s are for installing from homebrew, and 1s is saving the cache after the job.

The macOS job is really short, but the limit on the CI is the number of concurrent jobs, so shortening a fast job will still enable some other job to start sooner.

The ccache measures to ~20M on the machine, but that compresses to 8.8M in the cache area on Github, so I don't consider the space cost prohibitive.

I think this PR is ready to be merged to main now, and the ccache support for the Linux runners can be added later.

**Comment by keith-packard** [comment]
sounds good. should be ready to merge in a few hours.

**Comment by pjonsson** [comment]
I tested #550 rebased on top of main, and the test that I ran passed. I'll push an update for that PR after you have merged this.

**Pull request merged**
