### PR TITLE
Separate GitHub caches for each workflow

### PR DESCRIPTION
**Pull request by keith-packard**
Attempts to share the same cache cause collisions when the workflows
are executing at the same time. While less efficient, this should make
workflows run more reliably.

### CODE REVIEW

**Comment by yashi** [comment]
> Attempts to share the same cache cause collisions when the workflows are executing at the same time.

What symptom do you see?  Care to share a URL to a failed action?

**Comment by keith-packard** [comment]
> > Attempts to share the same cache cause collisions when the workflows are executing at the same time.
> 
> What symptom do you see? Care to share a URL to a failed action?

Two cache actions running in parallel will both finish about the same time, but only one will start the upload. The other will terminate with a warning about being unable to upload the cache file. At that point, the jobs start and (because the cache job finished quickly), they will fail to find the cached bits as they haven't *finished* getting uploaded. This happens almost every time the cache needs to be rebuilt.

I can't find a failed action because I routinely go and re-run all of the jobs, which works as the cache file is now present.

I would have thought the cache operations were atomic, but it's pretty clear that the process of uploading is not.

**Comment by keith-packard** [comment]
ok, so that didn't work out -- I'm betting the total space used was larger than available. Maybe I should try serializing the workflows so there's only a single one for the whole system? At least they might finish reliably then?

**Comment by keith-packard** [comment]
Ok, it looks like sticking everything in one giant workflow works; it just takes about four hours to run all of the jobs. We might consider removing some configuration flexibility in the library at some point, and then reducing the number of build variations to make this a bit faster. Four hours without random failures is better than two hours with rare successful builds though?

**Comment by yashi** [comment]
Well, yes, an unreliable CI isn't worth it.

Maybe we should use Ubuntu 20.04 for most of the test so that we can reduce the duration of tests. And have one large serialized test with Debian testing, to verify that our code works with newer environment?

**Comment by keith-packard** [comment]
Ubuntu 20.04 doesn't have any of the tools we need pre-installed, so wouldn't we have to install those before running tests? And isn't it faster to use a docker container with everything pre-installed? I think the basic problem we're hitting is that we're doing a *lot* of testing as there are so many possible ways to configure and run the code. And I'm about to merge a PR that adds powerpc build testing (sadly, we don't yet have bare-metal boot code for this platform). Maybe we should consider removing some configuration options from the library so we could remove the related tests? I wonder if anyone is using the legacy stdio code at this point?

**Comment by rdiez** [comment]
By "legacy stdio" you probably mean the origional stdio code from Newlib.

Someone porting an existing application from Newlib to Picolibc would probably start with the "legacy stdio". The new tinystdio has lost positional argument support too.

I would test the "legacy stdio" at least once, on one platform, just to make sure it does not break inadvertently.

**Comment by keith-packard** [comment]
Yeah, unless we get rid of the code, we'll need to test it, and I can't see how we'd want to test it on fewer platforms than any other code as we often find platform-specific bugs.

I took a look at the test runtimes and they actually look about the same as the old mechanism (around four hours); we're really only limited by the number of parallel tasks github is willing to schedule.

**Comment by keith-packard** [comment]
> The new tinystdio has lost positional argument support too.

I've been thinking how this might be done without requiring a lot of extra code or any extra memory usage, and without much regard to performance. Something that could scan the format string and argument list to extract a particular argument seems like it could suffice. Each positional argument would then involve scanning the format string *and* the argument list, which would be pretty expensive, but wouldn't require any temporary storage.

**Comment by yashi** [comment]
> isn't it faster to use a docker container with everything pre-installed?

Yes. That was our motivation.  We can't access the old logs, which are already expired, but each test used to be installing required tools independently.  And that installing process was taking around 10 min IIRC.  It depends on a test performed but most tests finish less than 5 min. so the installation process was taking more than half for each test.  A unified docker image allowed us to reduce this time down to 2 min.  This is a good part.

But from other point of view, we can say that it still taking 2 min for each test. We have hundreds of tests and this two min piles up.  More on later.

A reason I've said using stock Ubuntu 20.04 is that if docker image creation is causing so much trouble It might be a good idea to accept the installation time and reduced the time spent in other part of the tests.

> there are so many possible ways to configure

Yes, this is our problem right now.  And even small software tend to fall in this configuration combination hell. As I said most tests we have finish in 2 or 3 min. But some takes more than 15 min to finish.  ie) in the fortify arm tests, there are 15 tests taking more than 15 min, which in total is 225 min.  Other tests are taking less than 3 min, which in total is 195 min.  Thus, the 15 tests are taking more than half of the total time.  IIRC, longer test time is due to multilib.

Simple tests seems to finish in a min from the recent test logs.  But they still need 2 min to setup test environment.  That is, we are spending 2/3 of time just for environment setup.  If we run all build and test in one environment, we can effectively remove all setup time and cut down to 1/3 of total test time.  If we do that, we can spend a bit longer time to setup the environment because we have hundreds of tests anyway and that hundreds of tests take longer than the time to setup our test environment.  With this, it goes full circle and back to "Using stock Ubuntu 20.04".

If we keep the current environment setup, I believe we should classify test patterns and just run important tests for each commit or PR.  We can always run full tests by cron event for daily or weekly if we want.

**Comment by keith-packard** [comment]
oh, so perhaps running multiple tests within the same container image. Yes, we could definitely do that; just need to run them in separate directories. That's a good idea.

**Pull request merged**
