### PR TITLE
tests: warning fixes for 16-bit int platforms

### PR DESCRIPTION
**Pull request by pjonsson**

### CODE REVIEW

**Comment by pjonsson** [comment]
The tests fail because ffs.c does not include stdint.h. The CI seems severely overloaded, so I'll refrain from pushing updates until I can address everything in one swoop.

I don't know to what extent the build performance matters for the CI, but I have ccache installed locally, and meson does not seem to pick that up for the cross compilation for some reason. Here's a grep from my build directory:
```shell
$ grep -r ccache .
./meson-info/intro-compilers.json:{"host": {"c": {"id": "gcc", "exelist": ["msp430-elf-gcc", "-nostdlib", "-mhwmult=none"], "linker_exelist": ["msp430-elf-gcc", "-nostdlib", "-mhwmult=none"], "file_suffixes": ["c"], "default_suffix": "c", "version": "9.3.1", "full_version": "msp430-elf-gcc (Mitto Systems Limited - msp430-gcc 9.3.1.11) 9.3.1", "linker_id": "ld.bfd"}}, "build": {"c": {"id": "gcc", "exelist": ["ccache", "cc"], "linker_exelist": ["cc"], "file_suffixes": ["c"], "default_suffix": "c", "version": "11.4.0", "full_version": "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0", "linker_id": "ld.bfd"}}}
./meson-logs/meson-log.txt:C compiler for the build machine: ccache cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
```
With respect to ccache, there's no difference between meson 1.2.1 installed via pip, and the meson 0.61.2-1 package in Ubuntu 22.04, they both seem to ignore it.

For tests that only build C code running on the 2 CPU Github CI Linux machines, my experience is a reduction from ~10 minutes to ~90 seconds when introducing ccache.

**Comment by pjonsson** [comment]
Since I mentioned ccache in this PR, I'll finish my train of thought. Here are the statistics for a no-debug build for arm:
```shell
$ ../picolibc/scripts/do-arm-configure -Dio-long-long=true -Dposix-io=false -Dnewlib-iconv-encodings=none -Dspecsdir=picolibc/arm  -Ddebug=false -Dprefix=/usr/local -Dtests=true
$ ninja
$ ccache -s
Cacheable calls:    40095 / 40098 (99.99%)
  Hits:              1100 / 40095 ( 2.74%)
    Direct:             0 /  1100 ( 0.00%)
    Preprocessed:    1100 /  1100 (100.0%)
  Misses:           38995 / 40095 (97.26%)
Uncacheable calls:      3 / 40098 ( 0.01%)
Local storage:
  Cache size (GiB):   0.3 /   5.0 ( 6.49%)
  Hits:              1100 / 40095 ( 2.74%)
  Misses:           38995 / 40095 (97.26%)
$ ccache -z
$ rm -rf *
# Repeat the same build.
$ ccache -s
Cacheable calls:    40095 / 40097 (100.0%)
  Hits:             34066 / 40095 (84.96%)
    Direct:         33033 / 34066 (96.97%)
    Preprocessed:    1033 / 34066 ( 3.03%)
  Misses:            6029 / 40095 (15.04%)
Uncacheable calls:      2 / 40097 ( 0.00%)
Local storage:
  Cache size (GiB):   0.4 /   5.0 ( 7.93%)
  Hits:             34066 / 40095 (84.96%)
  Misses:            6029 / 40095 (15.04%)
```
The Github CI machines don't have a lot of cores and each core is quite slow, so a 50+% hitrate would speed up the builds quite a  bit. Do you want a PR which adds ccache to the CI?

**Comment by keith-packard** [comment]
> Since I mentioned ccache in this PR, I'll finish my train of thought. Here are the statistics for a no-debug build for arm:
> 
> ```shell
> $ ../picolibc/scripts/do-arm-configure -Dio-long-long=true -Dposix-io=false -Dnewlib-iconv-encodings=none -Dspecsdir=picolibc/arm  -Ddebug=false -Dprefix=/usr/local -Dtests=true
> $ ninja
> $ ccache -s
> Cacheable calls:    40095 / 40098 (99.99%)
>   Hits:              1100 / 40095 ( 2.74%)
>     Direct:             0 /  1100 ( 0.00%)
>     Preprocessed:    1100 /  1100 (100.0%)
>   Misses:           38995 / 40095 (97.26%)
> Uncacheable calls:      3 / 40098 ( 0.01%)
> Local storage:
>   Cache size (GiB):   0.3 /   5.0 ( 6.49%)
>   Hits:              1100 / 40095 ( 2.74%)
>   Misses:           38995 / 40095 (97.26%)
> $ ccache -z
> $ rm -rf *
> # Repeat the same build.
> $ ccache -s
> Cacheable calls:    40095 / 40097 (100.0%)
>   Hits:             34066 / 40095 (84.96%)
>     Direct:         33033 / 34066 (96.97%)
>     Preprocessed:    1033 / 34066 ( 3.03%)
>   Misses:            6029 / 40095 (15.04%)
> Uncacheable calls:      2 / 40097 ( 0.00%)
> Local storage:
>   Cache size (GiB):   0.4 /   5.0 ( 7.93%)
>   Hits:             34066 / 40095 (84.96%)
>   Misses:            6029 / 40095 (15.04%)
> ```
> 
> The Github CI machines don't have a lot of cores and each core is quite slow, so a 50+% hitrate would speed up the builds quite a bit. Do you want a PR which adds ccache to the CI?

Each CI instance starts from scratch though, so I don't see how ccache would help?

**Comment by keith-packard** [comment]
> > Each CI instance starts from scratch though, so I don't see how ccache would help?
> 
> The easiest is to store the ccache cache in the same area that `actions/cache` use, and is already used for the docker images.

That sounds really helpful; do you want to try and cook something up? Meson should automagically use ccache if it finds it in $PATH, so all we should need to do is get it installed and configured to persist the cache across builds. We probably need a per-buildtype/per-buildvariant cache key so the cache will hold mostly useful bits?

**Comment by pjonsson** [comment]
> > > Each CI instance starts from scratch though, so I don't see how ccache would help?
> > 
> > 
> > The easiest is to store the ccache cache in the same area that `actions/cache` use, and is already used for the docker images.
> 
> That sounds really helpful; do you want to try and cook something up? Meson should automagically use ccache if it finds it in $PATH, so all we should need to do is get it installed and configured to persist the cache across builds. We probably need a per-buildtype/per-buildvariant cache key so the cache will hold mostly useful bits?

I'll make a PR, but it will take a few days, and then it will take a good while longer to see if it works since the CI runtimes seem to be measured in work days. (On a technical level, Meson doesn't work the way you describe when crosscompiling for some reason, but I can make it work for the CI.)

Last time I checked, there was 10 Gb of cache storage available on Github, so how to split that among jobs isn't immediately obvious, but I'll figure it out. Does the Zephyr Docker-image need the apt-get recommended packages, or should I start with a PR that reduces the Zephyr docker-image size with 800MB?

**Comment by keith-packard** [comment]
> > > > Each CI instance starts from scratch though, so I don't see how ccache would help?
> > > 
> > > 
> > > The easiest is to store the ccache cache in the same area that `actions/cache` use, and is already used for the docker images.
> > 
> > 
> > That sounds really helpful; do you want to try and cook something up? Meson should automagically use ccache if it finds it in $PATH, so all we should need to do is get it installed and configured to persist the cache across builds. We probably need a per-buildtype/per-buildvariant cache key so the cache will hold mostly useful bits?
> 
> I'll make a PR, but it will take a few days, and then it will take a good while longer to see if it works since the CI runtimes seem to be measured in work days. (On a technical level, Meson doesn't work the way you describe when crosscompiling for some reason, but I can make it work for the CI.)

Yeah, I discovered the same thing. Fortunately, there's a simple hack -- if you prepend 'ccache' to the compiler command in the cross control file, it will automatically remove it if it isn't available. I've got those changes pending here and will push them shortly.

> Last time I checked, there was 10 Gb of cache storage available on Github, so how to split that among jobs isn't immediately obvious, but I'll figure it out. Does the Zephyr Docker-image need the apt-get recommended packages, or should I start with a PR that reduces the Zephyr docker-image size with 800MB?

Good plan. We can back-fill any recommended packages that end up being needed. I did that with the linux image and, as you can see, it's a lot smaller now.

I'm also thinking about how to reduce the number of variants being tested; it might be good to merge the fortify-source and release builds into a single pass, and maybe we can reduce the build option variant list as well. I'd love to get CI running in under an hour again.

Thanks for your help with this; CI is wonderful, but when it slows down development to a few PRs per day, it can be very frustrating.

**Comment by keith-packard** [comment]
another option -- switch CI so that it runs all variants for a single target in a single run. With that, we'd get a lot of sharing between runs with ccache without needing to save/restore the cache (although that would help even more). It would mean that the 'large' targets (arm, riscv and (soon) m68k) would take a lot longer than the smaller targets, so CI might end up taking longer per PR, but as fewer instances would be running, we'd be able to process more PRs per day.

**Comment by pjonsson** [comment]
I think we have multiple tracks of work going for the CI updates, so I tried to summarize your thoughts and intentions concerning the CI in #554. Feel free to edit the ticket if I have misunderstood what you meant.

**Pull request merged**
