### PR TITLE
newlib/libm: keep libm with the full content

### PR DESCRIPTION
**Pull request by anchao**
## Summary

Reference:
https://github.com/picolibc/picolibc/pull/142

Some RTOS(e.g. https://github.com/apache/incubator-nuttx/tree/master/libs/libc) provide a full feature libc which is tightly couple with OS implementation, but lack the high quality math library implementation. In this case, it's important to link libm only instead libc which contain libm since there are many duplicated but different symbols, linker may select the wrong implementation without any warning.

## Testing

Meson:
picolibc/scripts/do-arm-configure

Cmake:
cmake -G Ninja -DCMAKE_TOOLCHAIN_FILE=cmake/TC-arm-none-eabi.cmake  -B build/
cmake --build build

Signed-off-by: chao an <anchao@xiaomi.com>

### CODE REVIEW

**Comment by anchao** [comment]
Fix ci fail, please retrigger the ci flow again, thanks!

**Comment by keith-packard** [comment]
> Fix ci fail, please retrigger the ci flow again, thanks!

Yup, I'll try to keep an eye on this and trigger CI as you work through integrating this change.

**Comment by keith-packard** [comment]
Hrm. I'm wondering if this behavior should be optional, so that toolchains that don't want to waste storage space with duplicate math library bits could avoid this? I'm also wondering if this behavior should be considered to conflict with the `-Dwant-math-errno=true` option as that places a dependency between libm and libc. Finally, I wonder how the application should be expected to find the header files associated with the picolibc math library. Those are installed with the rest of the libc headers as is required to match the C language spec, so you can't simply insert that path ahead of whatever libc header path you're using.

**Comment by xiaoxiang781216** [comment]
> Hrm. I'm wondering if this behavior should be optional, so that toolchains that don't want to waste storage space with duplicate math library bits could avoid this?

But the toolchain maintainer mayn't aware this option or prefer the default setting. On the other hand, the storage increase is small(<1MB).

> I'm also wondering if this behavior should be considered to conflict with the `-Dwant-math-errno=true` option as that places a dependency between libm and libc.

errno dependency is very easy to fix.

> Finally, I wonder how the application should be expected to find the header files associated with the picolibc math library. Those are installed with the rest of the libc headers as is required to match the C language spec, so you can't simply insert that path ahead of whatever libc header path you're using.

it can be achieved by -isystem:
```
-isystem /path/to/xxx/libc/include
```

**Comment by keith-packard** [comment]
> it can be achieved by -isystem:
> 
> ```
> -isystem /path/to/xxx/libc/include
> ```

yes, but that will end up mixing picolibc and native libc headers in some unknown collection. Picolibc's math.h includes a range of standard header files which might (or might not) be provided by the existing C library. It's just a very fragile situation which can generate a range of hidden failures. I'm glad it seems to work for you, but I'm surprised NuttX encourages this configuration.

I hadn't really thought about the complications that will probably arise with this mixed setup when I suggested this would be a simple change to picolibc.

I think a 'correct' solution would involve splitting the math library and remainder of the C library into completely separate systems using only standard interfaces between them so that the resulting math library would be independent from the C library. I don't think you could create a binary library that worked in this fashion though -- libm can still rely on C library interfaces like errno, which you could only do at the API (source) level.

**Comment by rdiez** [comment]
Duplicating code in libc and libm libraries is not a clean solution. If Picolibc wants to provide a libm for other projects, I think the best way is to provide a way to build just libm. The build script should then take a path to the headers of the external libc, in case things like printf or errno are needed in libm.

**Comment by keith-packard** [comment]
I think @rdiez is correct -- the only workable solution would be to create an entirely isolated build environment for the math library which could then be used atop another C library. That's a much larger project than suggested here, and while I'd be happy to take a look at such a proposal, I hesitate to make any promises about adopting it.

**Pull request closed without merging**
