### PR TITLE
run-riscv: detect required RISC-V extensions and enable in QEMU

### PR DESCRIPTION
**Pull request by arichardson**
When building picolibc with floating-point or compressed instructions
enabled, the current run-riscv defaults will result in tests failing due
to illegal instruction traps. In fact building picolibc for RV32 with
compressed instructions will actually result in QEMU crashing, see
https://gitlab.com/qemu-project/qemu/-/issues/1353. It turns out this crash
was triggered by run-riscv starting QEMU with c=false even though the code
contained compressed instructions.

This patch attempts to better detect the required RISC-V extensions needed
in QEMU by parsing the .riscv.attributes section in the ELF binary and
enabling all required extensions based on the Tag_RISCV_arch value in that
section which looks something like rv64i2p0_m2p0_a2p0_f2p0_d2p0_c2p0.
If readelf is not installed, we fall back to the existing defaults.

### CODE REVIEW

**Comment by keith-packard** [comment]
I'm fine with requiring readelf to run the tests; this seems like a much better mechanism than the current kludgefest.

**Comment by arichardson** [comment]
> I'm fine with requiring readelf to run the tests; this seems like a much better mechanism than the current kludgefest.

Sounds good, should I update this PR to remove the fallback logic?

**Comment by keith-packard** [comment]
> Sounds good, should I update this PR to remove the fallback logic?

That seems like the best plan to me -- the fallback logic is pretty terrible. I think this should allow us to remove the other Risc-V scripts at some point? (run-rv32imac and run-rv32imafdc) (if you want to make those changes as well, that would be fine, but don't feel obligated).

**Comment by arichardson** [comment]
> > Sounds good, should I update this PR to remove the fallback logic?
> 
> That seems like the best plan to me -- the fallback logic is pretty terrible. I think this should allow us to remove the other Risc-V scripts at some point? (run-rv32imac and run-rv32imafdc) (if you want to make those changes as well, that would be fine, but don't feel obligated).

Updated to remove those scripts. Should hopefully be good to merge now.

**Pull request merged**
