### PR TITLE
stdio: remove struct _reent in macro

### PR DESCRIPTION
**Pull request by 8U61ife**
Encounter error when use "-Dnewlib-fvwrite-in-streamio=true" option.

### CODE REVIEW

**Comment by keith-packard** [comment]
Fix looks reasonable. We'll need the CI scripts changed to actually test this path and make sure it works though. Do you need help with that?

**Comment by 8U61ife** [comment]
I am not familiar with CI script. But I can try later.

**Comment by keith-packard** [comment]
Happy to add that bit for you; let's see if it works.

**Comment by keith-packard** [comment]
Another question -- why are you using the legacy stdio support? Do you need some functionality present there but not in the tinystdio code? Or do you just need the additional performance offered by the inline getc/putc operations when using buffering?

**Review by keith-packard — APPROVED** [review]
The changes make sense and look good to me; if they pass testing, they're ready to merge.

**Comment by 8U61ife** [comment]
> Another question -- why are you using the legacy stdio support? Do you need some functionality present there but not in the tinystdio code? Or do you just need the additional performance offered by the inline getc/putc operations when using buffering?

Just some personal trivial reasons.

**Comment by keith-packard** [comment]
> Just some personal trivial reasons.

Ok, I was wondering if we needed to keep this around anymore, but it sounds like some people are still using it.

**Pull request merged**
