### PR TITLE
Docker Speed Enhancement

### PR DESCRIPTION
**Pull request by yashi**
Hope this one works.  This is related to #189.

### CODE REVIEW

**Comment by keith-packard** [comment]
This looks like it will be a huge speedup for the shorter runs! It looks like there are still a couple of debug bits left in (running du and df). Let me know when you're ready for this to get merged; maybe we'll get better build times now :-)

**Review by keith-packard — APPROVED** [review]
I looked at the build logs and this seems to do what it says, but I admit to not knowing much about the workflows semantics...

**Comment by yashi** [comment]
gha-cache

**Comment by yashi** [comment]
The cache is now 10 GB instead of 5.
https://github.blog/changelog/2021-11-23-github-actions-cache-size-is-now-increased-to-10gb-per-repository/

**Pull request merged**
