### PR TITLE
tinystdio: ungetc decrements file position indicator correctly

### PR DESCRIPTION
**Pull request by HanaMAshour**
According to the ISO/IEC_9899_1999, section: J.5.16 it is mentioned that there is a file position indicator that is decremented by each call of the ungetc function.

The value of the file position indicator was not directed to the right position, this issue is now handled in the ftell function so the file indicator is placed correctly after the function ungetc is called.
An "if" condition is added which checks on the value of unget and if it is not equal zero then ungetc function is called so the indicator will be decremented.

This is a simple testcase that shows the effect of this change:

```c

#include <stdio.h>
#include <string.h>

const char *str = "This is a string";

int main() {

    FILE *file;
    char first;
    long position, start;

    file = fopen( "testfile.dat", "wb" );
    if( file == NULL ) return 1; 
    fputs(str, file);
    fclose(file);

    file = fopen( "testfile.dat", "rb" );
    if(file == NULL) return 1;

    first = fgetc(file);
    printf("First character read: %c\n", first);

    start = ftell(file);
    printf("Position before ungetc: %ld\n", start);

    ungetc(first, file);  // Use ungetc to put the character back

    position = ftell(file);  // Check ftell position (should be 0 after ungetc if first character was read)
    printf("Position after ungetc: %ld\n", position);

    fclose(file);

    if (position == 0)
        printf("Test passed: ungetc and ftell working as expected.\n");
    else
        printf("Test failed: Incorrect position after ungetc.\n");

    return 0;
}
```

### CODE REVIEW

**Comment by keith-packard** [comment]
Please add your test case to the test/ directory, that way we'll be able to verify that the proposed change resolves the issue.

**Comment by keith-packard** [comment]
I've taken your test case and added that to the PR along with a switch to using `atomic_load` to fetch the unget value (as required when using stdatomic). Feel free to pull that pr (#719) apart as you like and mixing that into your branch.

**Comment by HanaMAshour** [comment]
> I've taken your test case and added that to the PR along with a switch to using `atomic_load` to fetch the unget value (as required when using stdatomic). Feel free to pull that pr (#719) apart as you like and mixing that into your branch.

I pulled the pr(#719) and merged it to my branch, I also changed the copyrights of the test : "test-ungetc-ftell.c"

**Comment by keith-packard** [comment]
This change was merged as PR #719

**Pull request closed without merging**
