### PR TITLE
aarch64: Support softfp ABI (aapcs-soft)

### PR DESCRIPTION
**Pull request by keith-packard**
This fixes up the accelerated math functions and setjmp implementation to support aarch64 targets without an FPU via the aapcs-soft ABI specification.

I've managed to get this code to compile with an unreleased version of llvm using these flags:
```
$ clang --target=aarch64-none-elf -march=armv8-r+nofp -mabi=aapcs-soft
```
However, I cannot figure out how to build a soft FPU libary using the llvm compiler-rt project; that steadfastly refuses to build unless there is already a toolchain capable of building executables for that target. As I'm trying to create such a toolchain, there's a bit of a bootstrapping problem here.

### CODE REVIEW

**Comment by BlamKiwi** [comment]
How are you trying to build Compiler RT? Through `<source>/llvm` or `<source>/runtimes`? Our toolchains build the compiler first and then do a runtimes build separately with the main project.

**Comment by keith-packard** [comment]
> How are you trying to build Compiler RT? Through `<source>/llvm` or `<source>/runtimes`? Our toolchains build the compiler first and then do a runtimes build separately.

I rashly assumed that building the compiler and libraries together (like gcc does) would actually work? Even separately, I'm unsure how this could work as the runtime cmake code that validates the compiler functionality appears to require a working runtime and C library. I'm not sure how building them separately could help with that, but I can give it a try.

**Comment by keith-packard** [comment]
> How are you trying to build Compiler RT? Through `<source>/llvm` or `<source>/runtimes`? Our toolchains build the compiler first and then do a runtimes build separately.

Any chance you could hook me up with a sample cmake line to build the compiler-rt library? I did something that seemed right, and yet it still ends with cmake trying to build an app with my clang++ which has no libraries:
```
CMake Error at /usr/share/cmake-3.29/Modules/CMakeTestCXXCompiler.cmake:73 (message):
  The C++ compiler

    "/opt/llvm/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: '/build/llvm-project/compiler-rt/build/CMakeFiles/CMakeScratch/TryCompile-v62MFF'
    
    Run Build Command(s): /bin/ninja -v cmTC_cb659
    [1/2] /opt/llvm/bin/clang++    -MD -MT CMakeFiles/cmTC_cb659.dir/testCXXCompiler.cxx.o -MF CMakeFiles/cmTC_cb659.dir/testCXXCompiler.cxx.o.d -o CMakeFiles/cmTC_cb659.dir/testCXXCompiler.cxx.o -c /build/llvm-project/compiler-rt/build/CMakeFiles/CMakeScratch/TryCompile-v62MFF/testCXXCompiler.cxx
    [2/2] : && /opt/llvm/bin/clang++  -fuse-ld=lld CMakeFiles/cmTC_cb659.dir/testCXXCompiler.cxx.o -o cmTC_cb659   && :
    FAILED: cmTC_cb659 
    : && /opt/llvm/bin/clang++  -fuse-ld=lld CMakeFiles/cmTC_cb659.dir/testCXXCompiler.cxx.o -o cmTC_cb659   && :
    ld.lld: error: unable to find library -lstdc++
    clang++: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.
```

**Comment by BlamKiwi** [comment]
I'm visiting family over the weekend, so I can't test these snippets until I get back.

1. Build your compiler etc. as usual.  

```
cmake ../llvm-project/llvm -DLLVM_ENABLE_PROJECTS='clang;lldb;lld' -DCMAKE_BUILD_TYPE=Release
make -j$(nproc)
```

2. Create a CMake toolchain file. 

The really important one is `CMAKE_TRY_COMPILE_TARGET_TYPE `, as it tells CMake to build a static library to test if the compiler is working.

```
set(CMAKE_SYSTEM_NAME               Generic)
set(CMAKE_SYSTEM_PROCESSOR          aarch64)
set(SYSTEM_TRIPLE                   aarch64-none-elf)

set(CMAKE_TRY_COMPILE_TARGET_TYPE   STATIC_LIBRARY)

set(CMAKE_AR                        ${CMAKE_SYSROOT}/bin/llvm-ar${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_ASM_COMPILER              ${CMAKE_SYSROOT}/bin/clang${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_ASM_COMPILER_TARGET       ${SYSTEM_TRIPLE} CACHE INTERNAL "")
set(CMAKE_C_COMPILER                ${CMAKE_SYSROOT}/bin/clang${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_C_COMPILER_TARGET         ${SYSTEM_TRIPLE} CACHE INTERNAL "")
set(CMAKE_CXX_COMPILER              ${CMAKE_SYSROOT}/bin/clang++${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_CXX_COMPILER_TARGET       ${SYSTEM_TRIPLE} CACHE INTERNAL "")
set(CMAKE_LINKER                    ${CMAKE_SYSROOT}/bin/ld.lld${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_OBJCOPY                   ${CMAKE_SYSROOT}/bin/llvm-objcopy${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_RANLIB                    ${CMAKE_SYSROOT}/bin/llvm-ranlib${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_SIZE                      ${CMAKE_SYSROOT}/bin/llvm-size${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_STRIP                     ${CMAKE_SYSROOT}/bin/llvm-strip${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_OBJDUMP                   ${CMAKE_SYSROOT}/bin/llvm-objdump${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_NM                        ${CMAKE_SYSROOT}/bin/llvm-nm${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")

set(COMPILER_FLAGS                      "-ffreestanding -nodefaultlibs -march=armv8-r+nofp -mabi=aapcs-soft")
set(CMAKE_C_FLAGS_INIT                  ${COMPILER_FLAGS} CACHE INTERNAL "")
set(CMAKE_CXX_FLAGS_INIT                ${COMPILER_FLAGS} CACHE INTERNAL "")
set(CMAKE_ASM_FLAGS_INIT                ${COMPILER_FLAGS} CACHE INTERNAL "")

set(LINKER_FLAGS                        "-fuse-ld=lld")
set(CMAKE_EXE_LINKER_FLAGS_INIT         ${LINKER_FLAGS} CACHE INTERNAL "")
set(CMAKE_SHARED_LINKER_FLAGS_INIT      ${LINKER_FLAGS} CACHE INTERNAL "")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
```
3. Perform a LLVM "Runtimes" Build. 

```
cmake ../llvm-project/runtimes  
        -DCMAKE_SYSROOT=<SYSROOT>
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_TOOLCHAIN_FILE=<TOOLCHAIN>.cmake
        -DLLVM_ENABLE_RUNTIMES="compiler-rt"
        -DLLVM_DIR=<LLVM_INSTALL_DIR>
        -DLLVM_DEFAULT_TARGET_TRIPLE=aarch64-none-elf
        -DCOMPILER_RT_INSTALL_LIBRARY_DIR=${CMAKE_BINARY_DIR}/lib 
        -DCOMPILER_RT_BUILD_BUILTINS=ON 
        -DCOMPILER_RT_BUILD_CRT=OFF 
        -DCOMPILER_RT_CRT_USE_EH_FRAME_REGISTRY=OFF 
        -DCOMPILER_RT_BUILD_SANITIZERS=OFF 
        -DCOMPILER_RT_BUILD_XRAY=OFF 
        -DCOMPILER_RT_BUILD_LIBFUZZER=OFF 
        -DCOMPILER_RT_BUILD_PROFILE=OFF 
        -DCOMPILER_RT_BUILD_MEMPROF=OFF 
        -DCOMPILER_RT_BUILD_ORC=OFF 
        -DCOMPILER_RT_BUILD_GWP_ASAN=OFF 
        -DCOMPILER_RT_BAREMETAL_BUILD=ON 
        -DCOMPILER_RT_DEFAULT_TARGET_ONLY=ON 
        -DCOMPILER_RT_USE_BUILTINS_LIBRARY=ON 

make -j$(nproc)
```

Some of the `LLVM` and `COMPILER_RT` flags might be superfluous, but it's pretty close to what our project is doing.

**Comment by keith-packard** [comment]
yup, got that working. I fixed a few runtime bugs and now most things are passing. I'm still tracking down an issue with atomics via the swph instruction -- they're crashing (exception 0x200). Work around is to use `-Datomic-ungetc=false -Datomic-signal=false`. With that, tests are all passing nicely.

**Comment by keith-packard** [comment]
ok, I was building with -march=armv8-r+nofp, and I was using cortex-a57 as the qemu model, which is armv8-a. Building with -march=armv8-a+nofp works just fine.

**Comment by keith-packard** [comment]
Found a clang bug: https://github.com/llvm/llvm-project/issues/97181 for which I've inserted a work-around, which should be benign even after the bug is fixed.

**Pull request merged**
